// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"ginana-blog/internal/config"
	"ginana-blog/internal/db"
	"ginana-blog/internal/server"
	"ginana-blog/internal/server/controller/admin"
	"ginana-blog/internal/server/controller/api"
	"ginana-blog/internal/server/controller/front"
	"ginana-blog/internal/server/router"
	"ginana-blog/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	gormDB, err := db.NewDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	memcache, err := db.NewMC(configConfig)
	if err != nil {
		return nil, nil, err
	}
	v, err := service.NewErrHelper()
	if err != nil {
		return nil, nil, err
	}
	serviceService, err := service.New(configConfig, gormDB, memcache, v)
	if err != nil {
		return nil, nil, err
	}
	cApi := api.New(serviceService)
	cFront := front.New(serviceService)
	cAdmin := admin.New(serviceService)
	application := router.InitRouter(serviceService, configConfig, cApi, cFront, cAdmin)
	httpServer, err := server.NewHttpServer(application, configConfig)
	if err != nil {
		return nil, nil, err
	}
	app, cleanup, err := NewApp(serviceService, httpServer)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var initProvider = wire.NewSet(config.NewConfig, db.NewDB, db.NewMC)

var svcProvider = wire.NewSet(service.NewErrHelper, service.New, db.NewCasbin)

var cProvider = wire.NewSet(front.New, admin.New, api.New)

var httpProvider = wire.NewSet(router.InitRouter, server.NewHttpServer)
