# Global 全局配置

appName = "GiNana"

version = "1.0.0"

configIsLocal = true

configPath = "../configs"

cacheExpire = "24h"

# ginMode: release, debug
ginMode = "debug"

enableGzip = true

enableTemplate = true

viewsPath = "../views"

staticDir = "static:../static"
