# Global 全局配置

appName = "GiNana"

version = "1.0.0"

configIsLocal = true

configPath = "../configs"

# irisLogLevel: disable, fatal, error, warn, info, debug
irisLogLevel = "debug"

enableGzip = true

enableTemplate = true

reloadTemplate = true

viewsPath = "../views"

staticDir = "static:../static"

sessionAndCookieExpire = "24h"

jwtSecret = "123123"
