basePath: /api
definitions:
  model.Captcha:
    properties:
      code:
        description: Code
        type: string
      image:
        description: 验证码图片
        type: string
    required:
      - code
    type: object
  model.JSON:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: 127.0.0.1:8000
info:
  contact: {}
  description: 基于GiNana的个人网站项目，默认端口：8000
  license:
    name: Apache 2.0
  title: GiNana
  version: 1.0.0
paths:
  /login/captcha:
    get:
      consumes:
      - application/json
      description: 获取验证码
      produces:
        - application/json
      responses:
        "200":
          description: data:image/png;base64,U3dhZ2dlciByb2Nrcw==
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.JSON'
      tags:
        - Login
  /login/captcha/check:
    post:
      consumes:
        - application/json
      description: 提前检查验证码
      parameters:
        - description: Check Captcha
          in: body
          name: captcha
          required: true
          schema:
            $ref: '#/definitions/model.Captcha'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.JSON'
      tags:
        - Login
swagger: "2.0"
